### ISSUE TITLE
Suricata as a lib 

### ISSUE THREAD

**Issue by Onotoko** [vipinpv85/DPDK_SURICATA-4_1_1#6]
Hello,
I am wondering why do we use suricata as a lib in DPDK instead of DPDK as a lib of suricata.

If so we can easy to handle suricata

**Comment by vipinpv85** [comment]
I am not fully clear with your query, but let me try

1. DPDK libraries can be built with `.so` or `.a` mode.
2. DPDK applications are built with dpdk libraries and other 3rd party libraries.
3. Suricata is built as an application with `main` present in `suricata.c`

[question] why do we use suricata as a lib in DPDK 
[Answer] Can you please point me to the location where you get this information? As far I can understand I invoke DPDK API in Suricata application (hence calling DPDK API in Suricata binary)

[question]  instead of DPDK as a lib of suricata.
[Answer] a couple of reason, Suricata has its own way of mgmt threads, worker threads, pipeline or load balancer model. I do not want to restrict or remove Suricata features. Hence treating `suricata-main` as master thread and `DPDK-threads` slave threads it is easier and cleaner.

**Comment by Onotoko** [comment]
@vipinpv85,
Thank you, 
It makes sense now. 

I want to build DPDK as load balancer, each application as suricata can run. That's why I ask you.

**Comment by vipinpv85** [comment]
[Question] can we use DPDK to run a load balancer as multiple instances of suricata
[Answer] is yes.

1. The physical interface on DPDK gets packets from the external world.
2. VHOST, TAP or KNI interface sends to the virtual interface.
3. Multiple suricata instances feed on the traffic on a virtual interface.

example: port 1 ==> DPDK load balancer ==> virtual instance "tap1, tap2, tap3"

suricata 1 uses tap1
suricata 2 uses tap2
suricata 3 uses tap3

**Comment by Onotoko** [comment]
Thank you for kindly 

I will do DPDK load balancer with suricata, bro.

**Comment by vipinpv85** [comment]
if you are interested to help, please update the code base as a separate tag. This will help other too.

**Comment by Onotoko** [comment]
Thank you,

I will create new repo on my github and do it.

**Comment by vipinpv85** [comment]
sure, once you are comfortable with the code changes you can share git pull request to merge

**Comment by vipinpv85** [comment]
> Thank you,
> 
> I will create new repo on my github and do it.

are there any code contributions from your end?

**Comment by Onotoko** [comment]
@vipinpv85,
I have made 2 repositories for dpdk & suricata on my github 

https://github.com/Onotoko/dpdk-gateway

Hopefully, it can help who needs to start working on this field

**Comment by vipinpv85** [comment]
hi @Onotoko are you sharing your code to the current repository via git pull? or is your ask something different?

**Comment by vipinpv85** [comment]
@Onotoko 

1. dpdk-gateway is supposed to clone packets, so this means this is going to be used for only Suricata IDS mode (copy packet).

2. suricata-dpdk
a. ReceiveDpdkLoop -  is running infite for loop, you need not do this
b. configure_tx_buffer - you have enabled tx callback, what will be real advantage of invoking yet another function in run loop?
c. DpdkProcessPacket - is not using zero copy, it is still fetching from the SC heap
d. DpdkDumpCounters - `dtv->livedev` is per worker thread or multiple worker using same device?
e. configure - is created by `autoconf` so why is it committed with changes?
f. configure.ac - should this be ` DPDK support:                         ${enable_dpdk}` rather than `PF_RING support:                         ${enable_dpdk}`
g. source-dpdk.h - not sure if this right way of having the linkedlist
h. source-dpdk.c - ReceiveDpdkLoop any specific reason for still using ring?

**Comment by vipinpv85** [comment]
way I see the code base https://github.com/Onotoko/suricata-dpdk has taken up the idea and code from the original repository and hacked it to `PF_RING`.

as far I can understand PF_RING uses customized kernel driver and userspace topology. I am not sure if have permission to change the code based managed by

* \author William Metcalf <william.metcalf@gmail.com>
 * \author Eric Leblond <eric@regit.org>

**Comment by vipinpv85** [comment]
@Onotoko reach out to be on skype or hangout.

**Comment by Onotoko** [comment]
@vipinpv85
1. `dpdk-balancer` is responsible for receiving the packet from NIC and load balancer to others application as suricata, ...

2. `suricata-dpdk` is a slave process, will read all packets from a ring (when dpdk-balancer pushes in) and handle it.

Yes I based on the idea of pf_ring handle in suricata

**Comment by vipinpv85** [comment]
@Onotoko As updated the solution works only for IDS and IPS mode. Suricata workers are the bottleneck, and using `rte_pktmbuf_clone` you have added overhead of late free. 

you could have achieved the same with `rte_mbuf_refcnt_update`

**Comment by Onotoko** [comment]
@vipinpv85,

`Suricata workers are the bottleneck, and using rte_pktmbuf_clone you have added overhead of late free.` -> What did you mean while  each thread of suricata will use another ring repectively?

 `you could have achieved the same with rte_mbuf_refcnt_update` -> You mean I can use  rte_mbuf_refcnt_update` instead of `rte_pktmbuf_clone`?

`DpdkProcessPacket - is not using zero copy, it is still fetching from the SC heap` -> I was thinking zero copy will use in another situation 

` I am not sure if have permission to change the code based managed by` -> I added them to the header of file

**Comment by vipinpv85** [comment]
@Onotoko current code in dpdk-gateway `process_packets` is invoked which round-robins packets across rx_rings. This leads to workers getting flow-A on different worker-threads, leading to DPDk worker thread flow lock and reassembly locks. 

Sharing the same set of issues as pointed out in 

> https://github.com/vipinpv85/DPDK_SURICATA-4_1_1/issues/2

**Comment by Onotoko** [comment]
@vipinpv85,
Thank you  information,
` round-robins packets across rx_rings` -> I am using RSS value to load balancer. I am considering  around  using 5 tuples for it

**Comment by vipinpv85** [comment]
> @vipinpv85,
> 
> `Suricata workers are the bottleneck, and using rte_pktmbuf_clone you have added overhead of late free.` -> What did you mean while each thread of Suricata will use another ring respectively?
> 
> `you could have achieved the same with rte_mbuf_refcnt_update` -> You mean I can use rte_mbuf_refcnt_update`instead of`rte_pktmbuf_clone`?
> 
> `DpdkProcessPacket - is not using zero copy, it is still fetching from the SC heap` -> I was thinking zero copy will use in another situation
> 
> ` I am not sure if have permission to change the code based managed by` -> I added them to the header of file

1. I have evaluated your ideas and shared responses. 
2. Issues with Primary-Secondary model in DPDK.
3. I did not hear from you or any git pull merge request.
4. What is your ask from me?

**Comment by Onotoko** [comment]
`4. What is your ask from me?` -> No, I mean I added all author at beginning of a header file

`3. I did not hear from you or any git pull merge request.` ->  I am making the different solution with you, so I made another repository instead of making a pull request from you 

`1.I have evaluated your ideas and shared responses` -> got it, I still have not a good solution fo rit 

`2. Issues with Primary-Secondary model in DPDK.`-> Yes, but I have no choice now

**Comment by vipinpv85** [comment]
> @vipinpv85,
> Thank you information,
> ` round-robins packets across rx_rings` -> I am using RSS value to load balancer. I am considering around using 5 tuples for it

5 tuples suffers from same problem as discussed above

**Comment by vipinpv85** [comment]
> `4. What is your ask from me?` -> No, I mean I added all author at beginning of a header file
> 
> `3. I did not hear from you or any git pull merge request.` -> I am making the different solution with you, so I made another repository instead of making a pull request from you
> 
> `1.I have evaluated your ideas and shared responses` -> got it, I still have not a good solution fo rit
> 
> `2. Issues with Primary-Secondary model in DPDK.`-> Yes, but I have no choice now

if you really intend to collaborate you would have a clone, branched and push changes as git merge. I do not see them

**Comment by Onotoko** [comment]
> > @vipinpv85,
> > Thank you information,
> > ` round-robins packets across rx_rings` -> I am using RSS value to load balancer. I am considering around using 5 tuples for it
> 
> 5 tuples suffers from same problem as discussed above

I see it is really a hard problem when I want to use the primary-secondary model, but I have seen rss solution is really good for now

**Comment by Onotoko** [comment]
> > `4. What is your ask from me?` -> No, I mean I added all author at beginning of a header file
> > `3. I did not hear from you or any git pull merge request.` -> I am making the different solution with you, so I made another repository instead of making a pull request from you
> > `1.I have evaluated your ideas and shared responses` -> got it, I still have not a good solution fo rit
> > `2. Issues with Primary-Secondary model in DPDK.`-> Yes, but I have no choice now
> 
> if you really intend to collaborate you would have a clone, branched and push changes as git merge. I do not see them

As I mentioned above, your model and my model are not the same. so cannot pull or push anything

**Comment by vipinpv85** [comment]
> > > `4. What is your ask from me?` -> No, I mean I added all author at beginning of a header file
> > > `3. I did not hear from you or any git pull merge request.` -> I am making the different solution with you, so I made another repository instead of making a pull request from you
> > > `1.I have evaluated your ideas and shared responses` -> got it, I still have not a good solution fo rit
> > > `2. Issues with Primary-Secondary model in DPDK.`-> Yes, but I have no choice now
> > 
> > 
> > if you really intend to collaborate you would have a clone, branched and push changes as git merge. I do not see them
> 
> As I mentioned above, your model and my model are not the same. so cannot pull or push anything

@Onotoko if you think this is true, I am happy to tell you observation is incorrect

**Comment by vipinpv85** [comment]
for your information, work item shared with Suricata team

Summary: description on DPDK build, library and run mode integration into dev branch of Suricata

Introduction:
1. DPDK is set of Hardware and Software library, that helps to run on userspace.
2. DPDK process is classified as Primary & Secondary, where huge pages and devices are shared between them.
3. For an existing application to be support DPDK; both build and code is to be changed.
4. One can skip the DPDK lcore-threads and service-threads too. But has to invoke `rte_eal_init` and relevant library call.

image.png

What mode to use: (to be decided - which one to support and start)

1. Primary (singleton/monolithic):
Pros:
a) Suricata will run as Primary managing all DPDK PMD and Libraries.
b) Requires access to hugepages and root permission.
c) Does not need ASLR to be disabled.
d) can run in baremetal CPU, VM, Docker too.
e) can make use DPDK secondary apps like proc-info, pdump, any other custom secondary application.
Cons:
a) pausible to run as non root, but requires DPDK familirity.
b) code becomes bulky.
c) HW vendor or device offload, code needs to updated with generic API or SW fallback.

2. Seocndary:
Pros:
a) Suricata will run as Secondary with zero or a little managment and setup code for PMD and Libraries.
b) Requires access to hugepages and root permission.
c) ASLR needs to be disabled, for consistent or hiigher chance of start.
d) can run in baremetal CPU, VM, Docker too.
e) Code becomes lighter.
Cons:
a) plausible to run as non-root, but requires DPDK familiarity.
b) cannot make use of DPDK secondary apps like proc-info, pdump, any other custom secondary application.
c) Need to probe the configuration settings for HW vendor or device offload.

3. Detached Primary:
Pros:
a) Suricata will run as Primary, getting packets from another DPDK primary via memif/vhost/AF_XDP interface.
b) Requires access to huge pages and root permission.
c) can run in bare-metal CPU, VM, Docker too.
d) Code becomes lighter because we are using SW generic NIC and offloads.
e) all vendor-specific and non DPDK offloads can be run on the alternative process.
f) Useful in scenarios where selected packet mirror can be implemented in HW, or SW and fed to DPDK.
g)
Cons:
a) plausible to run as non-root, but requires DPDK familiarity.
b) secondary apps like proc-info, pdump, any other custom secondary application works.
c) can make use of XDP (eBPF) to redirect selected traffic too.

How to do:
1. There are ABI and API changes across DPDK releases.
2. Use a long term stable release as de-facto for DPDK. example 19.11.1 LTS.
3. Depending upon individual or distro releases not all NIC, HW or features are enabled.
4. Identify and choose the most common NIC like memif/Pcap/tap/vhost for ease of build.
5. Update `configure.ac` to reflect
a) $RTE_SDK & $RTE_TARGET for custom or distro dpdk package.
b) edit for new field `--enable-dpdk` as flag
c) add necessary changes for CFLAGS and LDFLAGS if flag is enabled.
6. Add Compiler flag `HAVE_DPDK` to build for DPDK mode.
7. Start for single and multi worker mode.
8. Code changes in
a) suricata.c: for DPDK initialization, run-mode registration, parse of suricata.yaml for DPDK sections and add-hook to Rules Add for DPDK ACL.
b) source-dpdk, run mode-dpdk: new files to support DPDK configuration and worker threads.

Proof of concept with single worker mode: https://github.com/vipinpv85/DPDK-Suricata_3.0
ongoing work with multi-worker: https://github.com/vipinpv85/DPDK_SURICATA-4_1_1

Performance: by redirecting rule match packets to worker threads
1. 1 worker can perform around 2.5 Mpps
2. 10Gbps with line rate (64byte) we need to 6 workers with each worker having 2.5Mpps flows
3. 40Gbps with line rate (128byte) we need 16 worker threads with 2.5Mpps flows each.

**Comment by Onotoko** [comment]
@vipinpv85,
Oh I see, I am adding ACL & ndpi as well to dpdk-balancer too.

We have the same observation

**Comment by vipinpv85** [comment]
> @vipinpv85,
> Oh I see, I am adding ACL & ndpi as well to dpdk-balancer too.
> 
> We have the same observation

this is already done

**Comment by Onotoko** [comment]
`this is already done`

You are done with it @vipinpv85?

**Comment by vipinpv85** [comment]
> `this is already done`
> 
> You are done with it @vipinpv85?

did not follow you, it is there in repository https://github.com/vipinpv85/DPDK-Suricata_3.0.

**Comment by Onotoko** [comment]
Sorry, I no have time for tracking your progress on your repositories so I don't know you are done with acl and ndpi. 

I only work as my knowledge :)

**Comment by vipinpv85** [comment]
> Sorry, I no have time for tracking your progress on your repositories so I don't know you are done with acl and ndpi.
> 
> I only work as my knowledge :)

perfect :), I do not have time for asking or tracking every day where are you, are you contributing, are you stuck etc. 

Based on your reply today, I have updated you. 

note: I work based on spare time on this codebase, which is used by students, faculties, companies and others. So my answer is same for you, I do not understand what is your ask from me?

**Comment by vipinpv85** [comment]
best wishes

**Comment by Onotoko** [comment]
`I do not understand what is your ask from me?` -> Before I start working with dpdk + suricata, I did search on the internet and I saw your source. That why I made this issue (Just want to get help from the previous person for right direction) 

Thanks in advance

**Comment by vipinpv85** [comment]
> `I do not understand what is your ask from me?` -> Before I start working with dpdk + suricata, I did search on the internet and I saw your source. That why I made this issue (Just want to get help from the previous person for right direction)
> 
> Thanks in advance

My friend, this is a section for issues. your question was never an issue, but idea/suggestion/brainstorm. So if there nothing as an issue, let me again say best wishes.
